# Generated by Django 4.2.13 on 2024-07-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('proposed_market_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('property_type', models.CharField(max_length=10, null=True)),
                ('square_feet', models.IntegerField(default=2000)),
                ('year_built', models.IntegerField(default=2010)),
                ('private_pool', models.BooleanField(null=True)),
            ],
        ),
    ]
