# Generated by Django 4.2.13 on 2024-06-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('mls_number', models.CharField(max_length=20)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('square_feet', models.IntegerField()),
                ('lot_size', models.IntegerField()),
                ('year_built', models.IntegerField()),
                ('days_on_market', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('pending', 'Pending')], max_length=20)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
            ],
        ),
    ]
