# Generated by Django 4.2.13 on 2024-07-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='private_pool',
            field=models.BooleanField(null=True),
        ),
    ]
