# Generated by Django 4.2.13 on 2024-06-20 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_property_property_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='days_on_market',
        ),
        migrations.RemoveField(
            model_name='property',
            name='list_price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='property',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='mls_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sold_price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
    ]
